version: '3.7'

services:
 intervalo_app:
  env_file: .env
  build:
   args:
    user: ${USER}
    uid: ${UID}
   context: ./
   dockerfile: Dockerfile
  image: intervalo
  container_name: intervalo-app
  restart: unless-stopped
  working_dir: /usr/share/nginx/html
  volumes:
    - ${WORK_DIR_SRC}:/usr/share/nginx/html
  networks:
    - intervalo

 intervalo_db:
  image: mariadb
  container_name: intervalo-db
  restart: unless-stopped
  environment:
    MYSQL_DATABASE: intervalodb
    MYSQL_ROOT_PASSWORD: 123123
    MYSQL_PASSWORD: 123123
    MYSQL_USER: root
  volumes:
  - intervalodata:/var/lib/mysq
  ports:
  -  "3307:3306"
  networks:
  - intervalo

 nginx_intervalo:
  image: nginx
  env_file: .env
  volumes:
  - ${WORK_DIR_SRC}:/usr/share/nginx/html
  - ${WORK_DIR}:/etc/nginx/conf.d
  ports:
  -  "8085:80"
  networks:
  - intervalo

networks:
  intervalo:
    driver: bridge

volumes:
 intervalodata:
   name: intervalodata
   external: true
