version: '3.7'

services:
 librosapi_app:
  env_file: .env
  build:
   args:
    user: ${USER}
    uid: ${UID}
   context: ./
   dockerfile: Dockerfile
  image: librosapi
  container_name: librosapi-app
  restart: unless-stopped
  working_dir: /usr/share/nginx/html
  volumes:
    - ${WORK_DIR_SRC}:/usr/share/nginx/html
  networks:
    - lumen-api-network

 librosapi_db:
  image: mariadb
  container_name: librosapi-db
  restart: unless-stopped
  environment:
    MYSQL_DATABASE: librosapidb
    MYSQL_ROOT_PASSWORD: 123123
    MYSQL_PASSWORD: 123123
    MYSQL_USER: root
  volumes:
  - lumen-api-data:/var/lib/mysq
  ports:
  -  "3309:3306"
  networks:
  - lumen-api-network

 nginx_librosapi:
  image: nginx
  env_file: .env
  volumes:
  - ${WORK_DIR_SRC}:/usr/share/nginx/html
  - ${WORK_DIR}:/etc/nginx/conf.d
  ports:
  -  "9002:80"
  networks:
  - lumen-api-network

networks:
  lumen-api-network:
    driver: bridge

volumes:
 lumen-api-data:
   name: lumen-api-data
   external: true
